name: Build & Deploy (SFTP)

on:
  push:
    branches: [ main ]

concurrency:
  group: deploy-production
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build VitePress
        run: npx vitepress build src

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          host: ${{ secrets.FTP_HOST }}
          port: 22
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: ".vitepress/dist/*"
          remote_path: grapper-doc
          delete: true
          exclude: |
            **/.git*
            **/.DS_Store
